name: btlz-api
networks:
  #Сеть для общения nginx и api
  mp-api-net:
    external: true
    name: mp-api-net
  mp-next-net:
    external: true
    name: mp-next-net
  boto-net:
    external: true
    name: boto-net

services:

  nginx:
    container_name: mp-nginx
    build:
      context: ..
      dockerfile: prod/Dockerfile.nginx
    ports:
      - 80:80
      - 443:443

    networks:
      - mp-api-net
      - mp-next-net
      - boto-net

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/gzip.conf:/etc/nginx/gzip.conf:ro
      - ./nginx/conf.d/server-80.conf:/etc/nginx/conf.d/server-80.conf:ro
      - ./nginx/conf.d/server-443.conf:/etc/nginx/conf.d/server-443.conf:ro

      - ../certbot/conf/:/etc/nginx/ssl/:ro
      # - ../certbot/conf/live/btlz-api.ru/fullchain.pem:/etc/nginx/ssl/live/btlz-api.ru/fullchain.pem:ro
      # - ../certbot/conf/live/btlz-api.ru/privkey.pem:/etc/nginx/ssl/live/btlz-api.ru/privkey.pem:ro
      - ../certbot/www/:/var/www/certbot/:ro

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    restart: unless-stopped