name: btlz-nginx
networks:
  boto-net:
    external: true
    name: boto-net



services:

  nginx:
    container_name: btlz-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - boto-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/gzip.conf:/etc/nginx/gzip.conf:ro
      - ./nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf:ro
      # - ./certs/127.0.0.1/domain.crt:/etc/nginx/ssl/domain.crt:ro
      # - ./certs/127.0.0.1/domain.key:/etc/nginx/ssl/domain.key:ro
      - ./certs/127.0.0.1:/etc/nginx/ssl:ro
